# Generated by Django 6.0.3 on 2026-03-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkLab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('routers', models.PositiveIntegerField(default=2)),
                ('switches', models.PositiveIntegerField(default=2)),
                ('pcs', models.PositiveIntegerField(default=4)),
                ('vlan_count', models.PositiveIntegerField(default=2)),
                ('ip_scheme', models.CharField(default='192.168.0.0/16', max_length=64)),
                ('protocols', models.CharField(default='OSPF', max_length=200)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('topology_text', models.TextField()),
                ('topology_diagram', models.TextField()),
                ('cli_config', models.TextField()),
                ('verification_steps', models.TextField()),
                ('troubleshooting_guide', models.TextField()),
                ('learning_notes', models.TextField()),
                ('subnet_plan', models.TextField()),
                ('quiz', models.JSONField(default=list)),
                ('suggestions', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
