# Generated by Django 6.0.3 on 2026-03-06 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_networklab_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_hash', models.CharField(db_index=True, max_length=64)),
                ('prompt_text', models.TextField()),
                ('response_text', models.TextField()),
                ('model_name', models.CharField(default='gpt-4o-mini', max_length=120)),
                ('provider', models.CharField(default='openai', max_length=40)),
                ('cache_hit', models.BooleanField(default=False)),
                ('response_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
